twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  welcome-message: Welcome to the Binary Ears microservices.
  twitter-v2-base-url: https://api.twitter.com/2/tweets